export const SIGN_IN = {
    REQUEST: "SIGN_IN_REQUEST",
    SUCCESS: "SIGN_IN_SUCCESS",
    FAIL: "SIGN_IN_FAIL",
}

export const SIGN_UP = {
    REQUEST: "SIGN_UP_REQUEST",
    SUCCESS: "SIGN_UP_SUCCESS",
    FAIL: "SIGN_UP_FAIL",
}